# gpg --list-secret-keys
keys:
  # Users
  - &thobson 107DA02C7AE97B084746564B9F1FD9D87950DB6F
  # Hosts
  - &snowflake age1fkfanvqqcss4smhwv848x6rhdee7jjcstqxkzznw4g4l0y7jgyzsy2uv9h

creation_rules:
  # All systems
  - path_regex: systems/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *thobson
        age:
          - *snowflake
  
  # Just snowflake
  - path_regex: systems/snowflake/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *thobson
        age:
          - *snowflake
          
