# gpg --list-secret-keys
keys:
  # Users
  - &thobson 107DA02C7AE97B084746564B9F1FD9D87950DB6F
  # Hosts
  - &snowflake age1fkfanvqqcss4smhwv848x6rhdee7jjcstqxkzznw4g4l0y7jgyzsy2uv9h
  - &slushy age1h3pk7z9602cgmw82fasumft2vt2pfxw8yn245r3ax627ug528vrs2llzac

creation_rules:
  # All systems
  - path_regex: systems/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *thobson
        age:
          - *snowflake
          - *slushy
  
  # Just snowflake
  - path_regex: systems/snowflake/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *thobson
        age:
          - *snowflake
          
  # Just slushy
  - path_regex: systems/slushy/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
        - *thobson
        age:
        - *slushy
        