# gpg --list-secret-keys
keys:
  # Users
  - &thobson 107DA02C7AE97B084746564B9F1FD9D87950DB6F
  # Hosts
  - &snowflake age15x0xax3hlekmukvknwn4wksmywvr4ll4k48vrruvvadrx6aaygkqp4vtvg

creation_rules:
  # All systems
  - path_regex: systems/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *thobson
        age:
          - *snowflake
  
  # Just snowflake
  - path_regex: systems/snowflake/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *thobson
        age:
          - *snowflake
          
