# gpg --list-secret-keys
keys:
  # Users
  - &thobson 107DA02C7AE97B084746564B9F1FD9D87950DB6F
  # Hosts
  - &snowflake 1a8d8e64bbc65ac802e24f5908db9ae5cb4ed1a5

creation_rules:
  # All systems
  - path_regex: systems/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *thobson
          - *snowflake
  
  # Just snowflake
  - path_regex: systems/snowflake/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *thobson
          - *snowflake
          
