# gpg --list-secret-keys
keys:
  # Users
  - &thobson 107DA02C7AE97B084746564B9F1FD9D87950DB6F
  # Hosts
  - &snowflake age1e6f3afhnfc85r49lucey32j9fdercd0wsnnzave5tk86g9czry9sw25mr6

creation_rules:
  # All systems
  - path_regex: systems/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *thobson
        age:
          - *snowflake
  
  # Just snowflake
  - path_regex: systems/snowflake/secrets/[^/]+\.yaml$
    pgp: *thobson
    age: *snowflake
