# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.supportedFilesystems = [ "zfs" ];
  
  boot.kernelModules = [ "kvm-intel" ];
  #boot.extraModulePackages = [ pkgs.linuxPackages.v4l2loopback ];
  boot.supportedFilesystems = [ "zfs" ];

  # Fix ZFS scheduling
  services.udev.extraRules = ''
    ACTION=="add|change", KERNEL=="sd[a-z]*[0-9]*|mmcblk[0-9]*p[0-9]*|nvme[0-9]*n[0-9]*p[0-9]*", ENV{ID_FS_TYPE}=="zfs_member", ATTR{../queue/scheduler}="none"
  '';

  boot.kernelParams = [ "nohibernate" ]; # ZFS doesn't support hibernation - can lead to FS corruption
  # https://github.com/openzfs/zfs/issues/260

  hardware.cpu.intel.updateMicrocode = true;

  fileSystems."/" = {
    device = "rpool/root/nixos";
    fsType = "zfs";
  };

  fileSystems."/home" = {
    device = "rpool/home";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "rpool/nix";
    fsType = "zfs";
  };

  fileSystems."/persist" = {
    device = "rpool/nix-keep";
    fsType = "zfs";
  };


  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E9DC-014A";
    fsType = "vfat";
  };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  
  # Suspend video corruption
  #hardware.nvidia.powerManagement.enable = true;
}
