name: NixOS Rebuild Targets
on: [push]
jobs:
  rebuild_nixos:
    strategy:
      matrix:
        tailscale_target: [permafrost]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          use-cache: 'true'

      - name: NixOS Rebuild
        run: |
          tailscale ssh root@${{ matrix.tailscale_target }} nixos-rebuild switch --flake github:hexf/dotfiles/${{ github.sha }}#${{ matrix.tailscale_target }}
          